workflows:
  ios-project-debug:
    name: iOS debug
    environment:
      xcode: latest
      cocoapods: default
      vars:
        XCODE_PROJECT: "LubionGame.xcodeproj"
        XCODE_SCHEME: "LubionGame"
    scripts:
      - name: Build debug app
        script: |
          xcodebuild build -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - "LubionGame/App/**/*.app" # Update the artifact path to match your Info.plist location
    publishing:
      email:
        recipients:
          - jordie.juwono96@gmail.com
